/**
 * List of all Serial API command / response codes.
 */
export enum SerialAPICommand {
	FUNC_ID_SERIAL_API_GET_INIT_DATA = 0x02,
	FUNC_ID_SERIAL_API_APPL_NODE_INFORMATION = 0x03,
	FUNC_ID_APPLICATION_COMMAND_HANDLER = 0x04,
	FUNC_ID_ZW_GET_CONTROLLER_CAPABILITIES = 0x05,
	FUNC_ID_SERIAL_API_SET_TIMEOUTS = 0x06,
	FUNC_ID_SERIAL_API_GET_CAPABILITIES = 0x07,
	FUNC_ID_SERIAL_API_SOFT_RESET = 0x08,
	FUNC_ID_ZW_SEND_NODE_INFORMATION = 0x12,
	FUNC_ID_ZW_SEND_DATA = 0x13,
	FUNC_ID_ZW_GET_VERSION = 0x15,
	FUNC_ID_ZW_R_F_POWER_LEVEL_SET = 0x17,
	FUNC_ID_ZW_GET_RANDOM = 0x1c,
	FUNC_ID_ZW_MEMORY_GET_ID = 0x20,
	FUNC_ID_MEMORY_GET_BYTE = 0x21,
	FUNC_ID_ZW_READ_MEMORY = 0x23,
	FUNC_ID_ZW_SET_LEARN_NODE_STATE = 0x40,
	FUNC_ID_ZW_GET_NODE_PROTOCOL_INFO = 0x41,
	FUNC_ID_ZW_SET_DEFAULT = 0x42,
	FUNC_ID_ZW_NEW_CONTROLLER = 0x43,
	FUNC_ID_ZW_REPLICATION_COMMAND_COMPLETE = 0x44,
	FUNC_ID_ZW_REPLICATION_SEND_DATA = 0x45,
	FUNC_ID_ZW_ASSIGN_RETURN_ROUTE = 0x46,
	FUNC_ID_ZW_DELETE_RETURN_ROUTE = 0x47,
	FUNC_ID_ZW_REQUEST_NODE_NEIGHBOR_UPDATE = 0x48,
	FUNC_ID_ZW_APPLICATION_UPDATE = 0x49,
	FUNC_ID_ZW_ADD_NODE_TO_NETWORK = 0x4a,
	FUNC_ID_ZW_REMOVE_NODE_FROM_NETWORK = 0x4b,
	FUNC_ID_ZW_CREATE_NEW_PRIMARY = 0x4c,
	FUNC_ID_ZW_CONTROLLER_CHANGE = 0x4d,
	FUNC_ID_ZW_SET_LEARN_MODE = 0x50,
	FUNC_ID_ZW_ASSIGN_SUC_RETURN_ROUTE = 0x51,
	FUNC_ID_ZW_ENABLE_SUC = 0x52,
	FUNC_ID_ZW_REQUEST_NETWORK_UPDATE = 0x53,
	FUNC_ID_ZW_SET_SUC_NODE_ID = 0x54,
	FUNC_ID_ZW_DELETE_SUC_RETURN_ROUTE = 0x55,
	FUNC_ID_ZW_GET_SUC_NODE_ID = 0x56,
	FUNC_ID_ZW_REQUEST_NODE_NEIGHBOR_UPDATE_OPTIONS = 0x5a,
	FUNC_ID_ZW_EXPLORE_REQUEST_INCLUSION = 0x5e,
	FUNC_ID_ZW_REQUEST_NODE_INFO = 0x60,
	FUNC_ID_ZW_REMOVE_FAILED_NODE_ID = 0x61,
	FUNC_ID_ZW_IS_FAILED_NODE_ID = 0x62,
	FUNC_ID_ZW_REPLACE_FAILED_NODE = 0x63,
	FUNC_ID_ZW_GET_ROUTING_INFO = 0x80,
	FUNC_ID_SERIAL_API_SLAVE_NODE_INFO = 0xa0,
	FUNC_ID_APPLICATION_SLAVE_COMMAND_HANDLER = 0xa1,
	FUNC_ID_ZW_SEND_SLAVE_NODE_INFO = 0xa2,
	FUNC_ID_ZW_SEND_SLAVE_DATA = 0xa3,
	FUNC_ID_ZW_SET_SLAVE_LEARN_MODE = 0xa4,
	FUNC_ID_ZW_GET_VIRTUAL_NODES = 0xa5,
	FUNC_ID_ZW_IS_VIRTUAL_NODE = 0xa6,
	FUNC_ID_ZW_SET_PROMISCUOUS_MODE = 0xd0,
	FUNC_ID_PROMISCUOUS_APPLICATION_COMMAND_HANDLER = 0xd1,
}

export function serialApiCommandToString(x: number): string {
	if (typeof x !== "number") {
		return `<invalid SerialAPICommand '${x}'>`;
	}
	if (x in SerialAPICommand) {
		return SerialAPICommand[x];
	}
	return `0x${x.toString(16)}`;
}
