import debug from "debug";
import { EventEmitter } from "events";
import {
	CommandClassInfo,
	parseCommandClassInfo,
} from "../commands/commandClassInfo";
import { decodeParams } from "../commands/decode";
import { BitmaskType, LengthType, ParameterType } from "../commands/spec";
import { convertFromJsonParams } from "../commands/specHelpers";
import { Queue } from "../common/queue";
import {
	bufferToString,
	defer,
	enumToString,
	noop,
	timeout,
	toHex,
} from "../common/util";
import { IProtocol } from "./protocol";
import { SerialAPICommand } from "./serialApiCommand";

const log = debug("zwave:serialapi");

export interface SerialAPICapabilities {
	applVersion: number;
	applRevision: number;
	manufacturerId: number;
	manufacturerProductType: number;
	manufacturerProductId: number;
	supportedFunctions: Set<SerialAPICommand>;
}

const SERIAL_API_CAPABILITIES_PARAMS = convertFromJsonParams([
	{ type: ParameterType.Integer, length: 1, name: "applVersion", help: "" },
	{ type: ParameterType.Integer, length: 1, name: "applRevision", help: "" },
	{
		type: ParameterType.Integer,
		length: 2,
		name: "manufacturerId",
		help: "",
	},
	{
		type: ParameterType.Integer,
		length: 2,
		name: "manufacturerProductType",
		help: "",
	},
	{
		type: ParameterType.Integer,
		length: 2,
		name: "manufacturerProductId",
		help: "",
	},
	{
		type: ParameterType.Bitmask,
		length: 256 / 8,
		name: "supportedFunctions",
		help: "",
		bitmaskType: BitmaskType.NodeNumber, // Not the right type to use, but applies a bit offset of 1
	},
]);

export enum NodeCapabilityFlags {
	SlaveAPI = 0, // Otherwise ControllerAPI
	TimerSupported = 1,
	SecondaryController = 2, // Otherwise Primary
	IsSIS = 3,
}

export interface SerialAPIInitData {
	apiVersion: number;
	capabilities: Set<NodeCapabilityFlags>;
	nodes: Set<number>;
	chipType: number;
	chipVersion: number;
}

const SERIAL_API_INIT_DATA_PARAMS = convertFromJsonParams([
	{ type: ParameterType.Integer, length: 1, name: "apiVersion", help: "" },
	{ type: ParameterType.Bitmask, length: 1, name: "capabilities", help: "" },
	{
		type: ParameterType.Integer,
		length: 1,
		name: "nodesLength",
		help: "",
		isAutogenerated: true,
		lengthOf: { refs: ["nodes"] },
	},
	{
		type: ParameterType.Bitmask,
		name: "nodes",
		help: "",
		length: {
			lengthType: LengthType.ParameterReference,
			from: { ref: "nodesLength" },
		},
		bitmaskType: BitmaskType.NodeNumber,
	},
	{
		type: ParameterType.Integer,
		length: 1,
		name: "chipType",
		help: "",
	},
	{
		type: ParameterType.Integer,
		length: 1,
		name: "chipVersion",
		help: "",
	},
]);

export interface HomeAndNodeId {
	/**
	 * 4-byte home ID of chip connected to serial API.
	 */
	homeId: number;

	/**
	 * Z-Wave Node ID [1..232] of chip connected to serial API.
	 */
	nodeId: number;
}

const ZW_MEMORY_GET_ID_PARAMS = convertFromJsonParams([
	{ type: ParameterType.Integer, length: 4, name: "homeId", help: "" },
	{ type: ParameterType.Integer, length: 1, name: "nodeId", help: "" },
]);

export enum ZwLibraryType {
	StaticController = 0x01,
	Controller = 0x02,
	EnhancedSlave = 0x03,
	Slave = 0x04,
	Installer = 0x05,
	RoutingSlave = 0x06,
	BridgeController = 0x07,
	Dut = 0x08,
	AvRemote = 0x0a,
	AvDevice = 0x0b,
}

export interface ZwVersionInfo {
	libraryVersion: string;
	libraryType: ZwLibraryType;
}

const ZW_GET_VERSION_PARAMS = convertFromJsonParams([
	{ type: ParameterType.Text, length: 12, name: "libraryVersion", help: "" },
	{ type: ParameterType.Integer, length: 1, name: "libraryType", help: "" },
]);

export enum TransmitOptions {
	Ack = 0x01,
	AutoRoute = 0x04,
	Explore = 0x20, // reduce powerlevel by 6dB
}

enum TxStatus {
	Ok = 0x00,
	NoAck = 0x01, // Node may be sleeping
	Fail = 0x02, // Network busy
	NotIdle = 0x03, // TODO
	NoRoute = 0x04, // TODO
}

enum UpdateState {
	NodeInfoReceived = 0x84,
	NodeInfoReqDone = 0x82,
	NodeInfoReqFailed = 0x81,
	RoutingPending = 0x80,
	NewIDAssigned = 0x40,
	DeleteDone = 0x20,
	SucID = 0x10,
}

export interface NodeInfo {
	nodeId: number;
	basicClass: number; // TODO BasicDeviceClassEnum
	genericClass: number; // TODO GenericDeviceClassEnum
	specificClass: number; // 'subclass' within GenericDeviceClassEnum
	commandClasses: CommandClassInfo;
}

const ZW_SEND_DATA_TIMEOUT = 65 * 1000; // See INS13954-Instruction-Z-Wave-500-Series-Appl-Programmers-Guide-v6_81_0x.pdf, fig 9

export enum DestinationType {
	Singlecast,
	Broadcast,
	Multicast,
}

export interface RxStatus {
	routedBusy: boolean; // A response route is locked by the application
	lowPower: boolean; // Received at low output power level
	destinationType: DestinationType; // Single/broadcast/multicast frame received
	explore: boolean; // Received an explore frame
	foreignFrame: boolean; // The received frame is not addressed to this node (Only valid in promiscuous mode)
	foreignHomeId: boolean; // The received frame is received from a foreign HomeID. Only Controllers in Smart Start AddNode mode can receive this status
}

export interface SerialApiCommandEvent {
	rxStatus: RxStatus;
	sourceNode: number;
	command: Buffer;
}

export function rxStatusToString(rxStatus: RxStatus): string {
	return [
		DestinationType[rxStatus.destinationType],
		rxStatus.routedBusy ? ",routedBusy" : "",
		rxStatus.lowPower ? ",lowPower" : "",
		rxStatus.explore ? ",explore" : "",
		rxStatus.foreignFrame ? ",foreignFrame" : "",
		rxStatus.foreignHomeId ? ",foreignHomeId" : "",
	].join("");
}

function parseRxStatus(value: number): RxStatus {
	return {
		routedBusy: (value & 0b00000001) > 0,
		lowPower: (value & 0b00000010) > 0,
		destinationType: (value & 0b00001100) >> 2,
		explore: (value & 0b00011000) === 0b00010000,
		foreignFrame: (value & 0b01000000) > 0,
		foreignHomeId: (value & 0b10000000) > 0,
	};
}

interface CallbackListener<T> {
	mapper: (command: SerialAPICommand, params: Buffer) => T | undefined;
	resolve: (value: T | PromiseLike<T>) => void;
	reject: (err: Error) => void;
}

// Set of functions assumed to exist on the Serial API before we
// even tried to query it for its list of supported functions.
// Note: SERIAL_API_GET_CAPABILITIES is only supported starting from
// Serial API version 4, so this is actually not entirely correct,
// but I don't have older versions, and didn't try to figure out
// how to detect these older versions correctly.
const DEFAULT_SUPPORTED_FUNCTIONS = new Set([
	SerialAPICommand.SERIAL_API_GET_CAPABILITIES,
	SerialAPICommand.ZW_GET_VERSION,
	SerialAPICommand.SERIAL_API_GET_INIT_DATA,
	SerialAPICommand.ZW_MEMORY_GET_ID,
]);

export class SerialApiSoftResettedError extends Error {
	constructor() {
		super("reinitializing SerialApi due to protocol soft-reset");
	}
}

export enum SerialApiState {
	/**
	 * Waiting for init sequence to complete.
	 */
	Constructed,

	/**
	 * Busy initializing.
	 */
	Initializing,

	/**
	 * Initialized, ready to accept calls and process callbacks
	 * from Z-Wave chip.
	 */
	Ready,

	/**
	 * API closed, no further calls possible, no further events will
	 * be emitted.
	 * Because protocol closed, and/or error occurred.
	 */
	Closed,
}

export interface SerialApi {
	/**
	 * Z-Wave message (command) received on network.
	 */
	on(
		event: "command",
		listener: (command: SerialApiCommandEvent) => void
	): this;
	on(event: "error", listener: (error: Error) => void): this;
	on(event: "close", listener: () => void): this;
}

/**
 * Expose Z-Wave Serial API commands.
 *
 * These commands can be used to determine capabilities of the connected
 * Z-Wave device, send messages to the Z-Wave network (commands), etc.
 */
export class SerialApi extends EventEmitter {
	private _state = SerialApiState.Constructed;
	private _protocol: IProtocol;
	private _supportedFunctions: Set<SerialAPICommand> = DEFAULT_SUPPORTED_FUNCTIONS;
	private _capabilities?: SerialAPICapabilities;
	private _initData?: SerialAPIInitData;
	private _homeAndNodeId?: HomeAndNodeId;
	private _versionInfo?: ZwVersionInfo;
	private _callbackId: number = 0;
	private _requests = new Queue();
	private _callbackListener: CallbackListener<any> | undefined;

	/**
	 * Construct Serial API using given Z-Wave Serial Protocol encoder/decoder.
	 *
	 * After construction, call `init()` to ensure the API initializes itself
	 * correctly, and synchronous access to certain state is enabled.
	 *
	 * The given protocol must already be initialized.
	 * When the protocol is reset, after or during initialization of the Serial
	 * API, it will be closed and a new instance needs to be created.
	 *
	 * @param protocol Serial Protocol encoder/decoder, must be already initialized (i.e. soft/hard-resetted).
	 */
	constructor(protocol: IProtocol) {
		super();
		this._protocol = protocol;

		this._protocol.on("callback", (command, params) =>
			this._handleCallback(command, params)
		);
		this._protocol.on("reset", () => this._handleProtocolReset());
		this._protocol.on("error", (error) => this._handleProtocolError(error));
		this._protocol.on("close", () => this._handleProtocolClose());
	}

	/**
	 * Initialize SerialApi and return home id for connected controller.
	 *
	 * Afterwards, calls like `getNodes()`, `isController()` and `getHomeAndNodeId()`
	 * will be possible.
	 */
	public async init(): Promise<void> {
		log("initializing");
		this._state = SerialApiState.Initializing;
		await this.serialGetCapabilities(true);
		await this.zwGetVersion();
		await this.serialGetInitData(true);
		await this.zwMemoryGetId(true);
		this._state = SerialApiState.Ready;
		log("initialized");
	}

	/**
	 * Determine whether connected Z-Wave chip is controller or slave.
	 *
	 * The instance needs to be initialized with `init()` first.
	 */
	public isController(): boolean {
		this._verifyInitialized(this._initData);
		return !this._initData.capabilities.has(NodeCapabilityFlags.SlaveAPI);
	}

	/**
	 * Get set of nodes as reported in last `serialGetInitData()` or `init()` call.
	 *
	 * To refresh the node list (e.g. after inclusion), call `serialGetInitData(true)`.
	 *
	 * The instance needs to be initialized with `init()` first.
	 */
	public getNodes(): Set<number> {
		this._verifyInitialized(this._initData);
		return this._initData.nodes;
	}

	/**
	 * Get currently assigned home and node ID, as reported by last
	 * call to `zwMemoryGetId()` or `init()`.
	 *
	 * To refresh the node list (e.g. after inclusion), call `serialGetInitData(true)`.
	 *
	 * The instance needs to be initialized with `init()` first.
	 */
	public getHomeAndNodeId(): HomeAndNodeId {
		this._verifyInitialized(this._homeAndNodeId);
		return this._homeAndNodeId;
	}

	public getLibraryType(): ZwLibraryType {
		this._verifyInitialized(this._versionInfo);
		return this._versionInfo.libraryType;
	}

	/**
	 * Determine basic information about connected Z-Wave chip such
	 * as manufacturer/produce information, and which serial API functions are
	 * supported.
	 *
	 * Automatically called during init().
	 *
	 * @param forceRefresh (Optional) when false (default) returns cached info when available,
	 *                     when true, will always request fresh data from chip.
	 */
	public async serialGetCapabilities(
		forceRefresh: boolean = false
	): Promise<SerialAPICapabilities> {
		if (this._capabilities && !forceRefresh) {
			return this._capabilities;
		}
		const response = await this._request(
			SerialAPICommand.SERIAL_API_GET_CAPABILITIES
		);
		this._capabilities = decodeParams<SerialAPICapabilities>(
			SERIAL_API_CAPABILITIES_PARAMS,
			response
		);
		this._supportedFunctions = this._capabilities.supportedFunctions;
		const caps = this._capabilities;
		log(
			`serialGetCapabilities:`,
			`applicationVersion=${caps.applVersion}.${
				caps.applRevision
			} manufacturerId=0x${toHex(
				caps.manufacturerId,
				4
			)} manufacturerProductType=0x${toHex(
				caps.manufacturerProductType,
				4
			)} manufacturerProductId=0x${toHex(caps.manufacturerProductId, 4)}`
		);
		log(
			`serialGetCapabilities supported functions: [${[
				...caps.supportedFunctions.values(),
			].map((func) => SerialAPICommand[func] ?? `0x${toHex(func)}`)}]`
		);
		return this._capabilities;
	}

	/**
	 * Determine role of connected chip (controller/slave etc), serial API version
	 * and list of nodes stored in RAM (for controllers).
	 *
	 * Automatically called during init().
	 *
	 * @param forceRefresh (Optional) when false (default) returns cached info when available,
	 *                     when true, will always request fresh data from chip.
	 */
	public async serialGetInitData(
		forceRefresh: boolean = false
	): Promise<SerialAPIInitData> {
		if (this._initData && !forceRefresh) {
			return this._initData;
		}

		const response = await this._request(
			SerialAPICommand.SERIAL_API_GET_INIT_DATA
		);
		this._initData = decodeParams<SerialAPIInitData>(
			SERIAL_API_INIT_DATA_PARAMS,
			response
		);

		const init = this._initData;
		const roleText = init.capabilities.has(NodeCapabilityFlags.SlaveAPI)
			? "slave"
			: init.capabilities.has(NodeCapabilityFlags.SecondaryController)
			? "secondaryController"
			: `primaryController isSIS=${init.capabilities.has(
					NodeCapabilityFlags.IsSIS
			  )}`;
		// Determine readable chip name (INS12350-Serial-API-Host-Appl.-Prg.-Guide - section 7.4)
		let chipName: string = "unknown";
		switch (init.chipType) {
			case 0x01:
				switch (init.chipVersion) {
					case 0x02:
						chipName = "ZW0102";
						break;
				}
				break;
			case 0x02:
				switch (init.chipVersion) {
					case 0x01:
						chipName = "ZW0201";
						break;
				}
				break;
			case 0x03:
				switch (init.chipVersion) {
					case 0x01:
						chipName = "ZW0301";
						break;
				}
				break;
			case 0x04:
				switch (init.chipVersion) {
					case 0x01:
						chipName = "ZM0401/ZM4102/SD3402";
						break;
				}
				break;
			case 0x05:
				switch (init.chipVersion) {
					case 0x00:
						chipName = "ZW050x";
						break;
				}
				break;
		}
		log(
			`serialGetInitData:`,
			`apiVersion=${init.apiVersion}`,
			`role=${roleText}`,
			`chipType=0x${init.chipType.toString(16)}`,
			`chipVersion=0x${init.chipVersion.toString(16)}`,
			`chipName=${chipName}`,
			`nodes=[${[...init.nodes.values()]}]`
		);

		return this._initData;
	}

	/**
	 * Retrieve Home ID and Node ID from connected serial chip.
	 *
	 * @param forceRefresh (Optional) when false (default) returns cached info when available,
	 *                     when true, will always request fresh data from chip.
	 */
	public async zwMemoryGetId(
		forceRefresh: boolean = false
	): Promise<HomeAndNodeId> {
		if (this._homeAndNodeId && !forceRefresh) {
			return this._homeAndNodeId;
		}
		const response = await this._request(SerialAPICommand.ZW_MEMORY_GET_ID);
		this._homeAndNodeId = decodeParams<HomeAndNodeId>(
			ZW_MEMORY_GET_ID_PARAMS,
			response
		);
		const homeAndId = this._homeAndNodeId;
		log(
			`zwMemoryGetId: homeId=0x${toHex(
				homeAndId.homeId,
				8
			)} nodeId=${homeAndId.nodeId.toString()}`
		);
		return this._homeAndNodeId;
	}

	/**
	 * Obtain Z-Wave chip's library version in human-readable form,
	 * and what type it is.
	 */
	public async zwGetVersion(): Promise<ZwVersionInfo> {
		const response = await this._request(SerialAPICommand.ZW_GET_VERSION);
		this._versionInfo = decodeParams<ZwVersionInfo>(
			ZW_GET_VERSION_PARAMS,
			response
		);
		const info = this._versionInfo;
		log(
			`zwGetVersion: libraryVersion="${
				info.libraryVersion
			}" libraryType=${ZwLibraryType[info.libraryType]}`
		);
		return this._versionInfo;
	}

	/**
	 * Send Z-Wave command to specified node and wait for transmission
	 * to be acknowledged by it.
	 *
	 * @param nodeId Node ID to send data to, or 0xff to broadcast to all nodes
	 * @param payload Z-Wave command to transmit (minimum 1 byte)
	 * @param timeoutInMs Timeout of network request (not including any already pending requests), in milliseconds
	 */
	public async zwSendData(
		nodeId: number,
		payload: Buffer,
		timeoutInMs: number = ZW_SEND_DATA_TIMEOUT
	): Promise<void> {
		const funcId = this._getNextCallbackId();
		try {
			// TODO INS13954 4.3.3.1 Prevent sending to virtual nodes inside the controller/bridge itself
			// TODO INS13954 4.3.3.1.5 Implement checks for minimum/maximum payload size:
			// Transmit option             non-secure  S0 secure
			// TRANSMIT_OPTION_EXPLORE     46 bytes    26 bytes
			// TRANSMIT_OPTION_AUTO_ROUTE  48 bytes    28 bytes
			// TRANSMIT_OPTION_NO_ROUTE    54 bytes    34 bytes
			log(
				"zwSendData",
				`transaction=${funcId}`,
				`node=${nodeId}`,
				`payload=[${bufferToString(payload)}]`
			);
			// TODO Allow to specify TxOptions
			const txOptions =
				TransmitOptions.Ack |
				TransmitOptions.AutoRoute |
				TransmitOptions.Explore;
			const params = Buffer.from([
				nodeId,
				payload.length,
				...payload,
				txOptions,
				funcId,
			]);
			await this._requestAndWait(
				SerialAPICommand.ZW_SEND_DATA,
				params,
				timeoutInMs,
				(command: SerialAPICommand, params: Buffer) => {
					if (command !== SerialAPICommand.ZW_SEND_DATA) {
						return;
					}
					if (params.length < 2) {
						return;
					}
					// Spec: INS13954, 4.3.3.1.7
					if (params[0] !== funcId) {
						log(
							"warn",
							`unexpected callback ID received, ignoring`
						);
						return;
					}
					const txStatus: TxStatus = params[1];
					if (txStatus !== TxStatus.Ok) {
						throw new Error(
							`error sending command to node ${nodeId}: ${
								TxStatus[txStatus] ?? `0x${toHex(txStatus)}`
							}`
						);
					}
					let transmitTime: number | undefined;
					if (params.length >= 4) {
						// DevKit 6.51+ added time measurement to response
						transmitTime = params.readUInt16BE(2) * 10; // in ms
					}
					log(
						`zwSendData ok: transaction=${funcId}${
							transmitTime !== undefined
								? ` transmitTime=${transmitTime}ms`
								: ""
						}`
					);
					return true; // Need to return something to end mapper
				}
			);
		} catch (err) {
			log(`zwSendData failed: transaction=${funcId} error=`, err);
			// INS13954 4.3.3.1.6 Exception recovery:
			// If a timeout occurs, it is important to call ZW_SendDataAbort to stop the sending of the frame.
			// But let's do it also in any other case of aborting the transmission.
			try {
				await this.zwSendDataAbort();
			} catch {
				/* ignore follow-up error, ignore original error for clarity */
			}
			throw err;
		}
	}

	/**
	 * Abort in-progress zwSendData request.
	 *
	 * Only to be used by zwSendData() itself.
	 */
	public async zwSendDataAbort(): Promise<void> {
		await this._send(SerialAPICommand.ZW_SEND_DATA_ABORT);
	}

	public async zwRequestNodeInfo(
		nodeId: number,
		timeoutInMs: number = ZW_SEND_DATA_TIMEOUT
	): Promise<NodeInfo> {
		try {
			log(`zwRequestNodeInfo node=${nodeId}`);
			const params = Buffer.from([nodeId]);
			const nodeInfo = await this._requestAndWait(
				SerialAPICommand.ZW_REQUEST_NODE_INFO,
				params,
				timeoutInMs,
				(command: SerialAPICommand, params: Buffer) => {
					if (command !== SerialAPICommand.ZW_APPLICATION_UPDATE) {
						return;
					}
					if (params.length < 6) {
						return;
					}
					const bStatus = params[0];
					if (bStatus === UpdateState.NodeInfoReqFailed) {
						throw new Error(
							`node ${nodeId} did not respond with Node Information Frame`
						);
					}
					// TODO There's also NodeInfoReqDone, but no idea when you'd get one
					if (bStatus !== UpdateState.NodeInfoReceived) {
						return;
					}
					// INS13954-7 4.3.1.8 ApplicationControllerUpdate
					// Example response:
					// NodeID | bLen | basic | generic | specific | commandclasses[]
					// 10       1a     04      11        01         5e 20 86 72 26 5a 59 85 73 98 7a 56 70 31 32 8e 60 75 71 27 22 ef 2b
					const bNodeId = params[1];
					const bLen = params[2];
					const basicClass = params[3];
					const genericClass = params[4];
					const specificClass = params[5];
					const commandClassesRaw = params.slice(6);
					if (bNodeId !== nodeId) {
						return;
					}
					if (bLen !== params.length - 3 || bLen < 3) {
						return;
					}
					const commandClasses = parseCommandClassInfo(
						commandClassesRaw
					);
					return {
						nodeId,
						basicClass,
						genericClass,
						specificClass,
						commandClasses,
					};
				}
			);

			log(`zwRequestNodeInfo ok: node=${nodeId} result=`, nodeInfo);
			return nodeInfo;
		} catch (err) {
			log(`zwRequestNodeInfo failed: node=${nodeId} error=`, err);
			throw err;
		}
	}

	private _verifyCommandSupportedAndReady(command: SerialAPICommand): void {
		if (this._state === SerialApiState.Closed) {
			throw new Error(`Serial API closed`);
		}
		if (!this._supportedFunctions.has(command)) {
			if (this._state === SerialApiState.Ready) {
				throw new Error(
					`Serial API command ${enumToString(
						command,
						SerialAPICommand
					)} not supported by device`
				);
			} else {
				throw new Error(
					`Serial API command ${enumToString(
						command,
						SerialAPICommand
					)} possibly not supported by device: Serial API not initialized yet`
				);
			}
		}
	}

	private async _send(
		command: SerialAPICommand,
		params?: Buffer
	): Promise<void> {
		this._verifyCommandSupportedAndReady(command);
		return this._requests.add(() => this._protocol.send(command, params));
	}

	private async _request(
		command: SerialAPICommand,
		params?: Buffer
	): Promise<Buffer> {
		this._verifyCommandSupportedAndReady(command);
		return this._requests.add(() =>
			this._protocol.request(command, params)
		);
	}

	private async _requestAndWait<T>(
		command: SerialAPICommand,
		params: Buffer | undefined,
		timeoutInMs: number,
		mapper: (command: SerialAPICommand, params: Buffer) => T | undefined
	): Promise<T> {
		this._verifyCommandSupportedAndReady(command);
		return this._requests.add(async () => {
			const resultDef = defer<T>();
			if (this._callbackListener) {
				throw new Error(
					"programming error: callbackListener still present"
				);
			}
			this._callbackListener = {
				mapper,
				resolve: resultDef.resolve,
				reject: resultDef.reject,
			};
			// Prevent unhandled rejection if aborted before protocol.request() returns
			resultDef.promise.catch(noop);
			try {
				const commandResponse = await this._protocol.request(
					command,
					params
				);
				if (commandResponse.length < 1) {
					throw new Error(
						`command ${SerialAPICommand[command]} failed: got zero-length response from Z-Wave Serial device`
					);
				}
				if (commandResponse[0] === 0) {
					throw new Error(
						`command ${SerialAPICommand[command]} failed: request could not be queued`
					);
				}
				return await timeout(resultDef.promise, timeoutInMs);
			} finally {
				this._callbackListener = undefined;
			}
		});
	}

	private _handleCallback(command: SerialAPICommand, params: Buffer): void {
		if (this._callbackListener) {
			try {
				const mapper = this._callbackListener.mapper;
				const result = mapper(command, params);
				if (result !== undefined) {
					this._callbackListener.resolve(result);
					this._callbackListener = undefined;
				}
			} catch (err) {
				this._callbackListener?.reject(err);
				this._callbackListener = undefined;
			}
		}

		if (command === SerialAPICommand.APPLICATION_COMMAND_HANDLER) {
			const rxStatus = parseRxStatus(params[0]);
			const sourceNode = params[1];
			const cmdLength = params[2];
			const cmdPayload = params.slice(3, 3 + cmdLength);
			// const rxRSSIVal = params[params.length - 2];
			// const securityKey = params[params.length - 1];
			const event: SerialApiCommandEvent = {
				rxStatus,
				sourceNode,
				command: cmdPayload,
			};
			log("emit command", event);
			process.nextTick(() => this._safeEmit("command", event));
		}

		// TODO Handle FUNC_ID_SERIAL_API_STARTED to trigger _handleProtocolReset()?
		// I have no way to test this, because USB devices also disconnect from the USB
		// bus during a reset.
	}

	private _getNextCallbackId(): number {
		this._callbackId++;
		if (this._callbackId > 0xff) {
			// Note: not 0, because that means we don't want feedback
			this._callbackId = 1;
		}
		return this._callbackId;
	}

	private _verifyInitialized<T>(value: T | undefined): asserts value is T {
		if (this._state !== SerialApiState.Ready) {
			throw new Error(
				`SerialAPI is not initialized (currently in state ${
					SerialApiState[this._state]
				})`
			);
		}
		if (!value) {
			// Programming error
			throw new Error("internal error");
		}
	}

	private _handleProtocolReset(): void {
		if (
			this._state === SerialApiState.Closed ||
			this._state === SerialApiState.Constructed
		) {
			return;
		}
		this._abortAndClose(new Error("protocol reset"));
	}

	private _handleProtocolClose(): void {
		if (this._state === SerialApiState.Closed) {
			return;
		}
		log("close");
		this._state = SerialApiState.Closed;
		this._abort(new Error("protocol closed"));
		this._safeEmit("close");
	}

	private _handleProtocolError(error: Error): void {
		if (this._state === SerialApiState.Closed) {
			return;
		}
		this._abortAndClose(
			new Error(`protocol errored: ${error.name}: ${error.message}`)
		);
	}

	private _safeEmit(event: string, ...args: any[]): void {
		try {
			this.emit(event, ...args);
		} catch (err) {
			if (this._state === SerialApiState.Closed) {
				// No way to report it anymore, let it explode as uncaught error
				process.nextTick(() => {
					throw err;
				});
				return;
			}
			const error =
				typeof err === "object" && err instanceof Error
					? err
					: new Error("unknown error");
			const eventHandlerError = new Error(
				`error in SerialApi event handler for '${event}': ${error.name}: ${error.message}`
			);
			this._abortAndClose(eventHandlerError);
		}
	}

	private _abort(error: Error): void {
		this._protocol.cancel(error);
		if (this._callbackListener) {
			this._callbackListener.reject(error);
			this._callbackListener = undefined;
		}
		this._requests.abortPending(error);
	}

	private _abortAndClose(error: Error): void {
		if (this._state === SerialApiState.Closed) {
			// Ignore follow-up errors
			return;
		}
		log("error", error);
		this._state = SerialApiState.Closed;
		this._abort(error);
		this._safeEmit("error", error);
		log("close");
		this._safeEmit("close");
	}
}
